version: "3"

services:
  frontend:
    container_name: sufiashop-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_STRAPI_API_URL=http://localhost:1337
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_STRAPI_API_URL={{ NEXT_PUBLIC_STRAPI_API_URL }}
      - NEXT_PUBLIC_STRAPI_API_TOKEN={{ NEXT_PUBLIC_STRAPI_API_TOKEN }}
    ports:
      - "3000:3000"
    networks:
      - strapi