version: "3"

services:
  # Frontend service
  frontend:
    container_name: gosiyuan-frontend
    image: robiul692/gosiyuan-frontend
    build:
      context: ./frontend  # Assuming this compose file is at the project root
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_STRAPI_API_URL=http://strapi:1337  # Use service name, not localhost
        - NEXT_PUBLIC_STRAPI_API_TOKEN=${STRAPI_API_TOKEN}  # Use from .env file
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_STRAPI_API_URL=http://strapi:1337  # For runtime
      - NEXT_PUBLIC_STRAPI_API_TOKEN=${STRAPI_API_TOKEN}  # For runtime
    ports:
      - "3010:3000"
    networks:
      - strapi
    depends_on:
      - strapi  # Ensure Strapi starts first

networks:
  strapi:
    external: true
    name: Strapi  # Connect to existing network named "Strapi"