name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: docker pull robiul692/gosiyuan-frontend:latest
      - name: Delete Old docker container
        run: docker rm -f gosiyuan-frontend || true
      - name: Run Docker Container
        run: docker run -d --name gosiyuan-frontend \           
        --network=Strapi \
          -p 3010:3000 \
          -e NEXT_PUBLIC_STRAPI_API_URL=$NEXT_PUBLIC_STRAPI_API_URL \
          -e NEXT_PUBLIC_STRAPI_API_TOKEN=$NEXT_PUBLIC_STRAPI_API_TOKEN \
          robiul692/gosiyuan-frontend:latest
