name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      env:
        STRAPI_API_URL: ${{secrets.STRAPI_API_URL}}
        STRAPI_API_TOKEN: ${{secrets.STRAPI_API_TOKEN}}
      run: |
        docker build \
          --no-cache \
          --build-arg NEXT_PUBLIC_STRAPI_API_URL=$STRAPI_API_URL \
          --build-arg NEXT_PUBLIC_STRAPI_API_TOKEN=$STRAPI_API_TOKEN \
          -t robiul692/gosiyuan-frontend:latest .
          
    - name: Push to Dockerhub
      run: docker push robiul692/gosiyuan-frontend:latest